### ISSUE TITLE
Show-all button in the translation tool

### ISSUE THREAD

**Issue by manifroh** [magnolo/newhere#173]
The 'show all' option in the translation tool properly works only for the "angebote", in the other sections it sometimes worked, sometimes it didn't. Can't consistently reproduce (hence no screenshots).

also, the "categories" and "filter"-sections give you the following, if "show all" is unchecked

![image](https://cloud.githubusercontent.com/assets/24552403/22392450/a2bff248-e4f9-11e6-8b93-6a37dd699ae5.png)

**Comment by ScrambledRK** [comment]
could be related to #182. instead of the `/api/offer-translations/untranslated` query it is just `/api/offer-translations` taking a long time. 

Since the visual feedback of the tick appearing takes a long time, you may press twice and immediately discard the current query. (checkbox unticked) When that happens I get several Syntax Error. When I check the box again I get the list but every entry is a grey "edit" text.

> Error: [$parse:syntax] Syntax Error: Token ']' is an unexpected token at column 87 of the expression ['Übersetzen nach %s (%s)' | translate | sprintf: vm.language.i18n:vm.language.language]] starting at []].

"Angebote" might work more reliable because it still has untranslated entries?
